package org.c4rth.virtual.rest;

import io.micrometer.observation.Observation;
import io.micrometer.observation.ObservationRegistry;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.apache.coyote.BadRequestException;
import org.c4rth.virtual.domain.Book;
import org.c4rth.virtual.domain.dto.BookDTO;
import org.c4rth.virtual.repository.BookRepository;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Random;
import java.util.UUID;
import java.util.stream.Collectors;

/**
 * Generated by Springboot-3layer-Generator at Jan 6, 2021, 8:30:41 PM
 */
@RestController
@RequestMapping("/books")
@RequiredArgsConstructor
@Slf4j
public class BookController {

    private final BookRepository bookRepository;
    private final ObservationRegistry observationRegistry;

    @GetMapping(produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<List<BookDTO>> getAll() {

        Observation observation = Observation.start("getAll", observationRegistry);

        UUID uuid = UUID.randomUUID();
        log.info("getAll() {} running", uuid);

        Random random = new Random();
        if (random.nextInt(1000) > 900) {
            log.error("getAll() failed");
            throw new RuntimeException("simulated error getAll");
        }

        ResponseEntity<List<BookDTO>> list = ResponseEntity.ok(this.bookRepository.findAll().stream().
                map((e) -> new BookDTO(e.getBookId(),e.getAuthor(),e.getIsbn(),e.getTitle(),e.getYear())).collect(Collectors.toList()));

        log.info("getAll() {} executed", uuid);

        observation.stop();

        return list;
    }

    @GetMapping(value = "/simple", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<List<Book>> getAllSimple() {

        Observation observation = Observation.start("getAllSimple", observationRegistry);

        Random random = new Random();
        if (random.nextInt(1000) > 900) {
            log.error("getAllSimple() failed");
            throw new RuntimeException("simulated error getAllSimple");
        }

        observation.stop();

        return ResponseEntity.ok(this.bookRepository.findAll());
    }

    @PostMapping(produces = MediaType.APPLICATION_JSON_VALUE, consumes = MediaType.APPLICATION_JSON_VALUE)
    @Transactional
    public ResponseEntity<BookDTO> saveBook(@RequestBody BookDTO dto) {

        Observation observation = Observation.start("saveBook", observationRegistry);

        UUID uuid = UUID.randomUUID();
        log.info("saveBook() {} running", uuid);


        Random random = new Random();
        if (random.nextInt(1000) > 900) {
            log.error("saveBook() failed");
            throw new RuntimeException("simulated error saveBook");
        }

        Book e = new Book();
        e.setBookId(dto.bookId());
        e.setIsbn(dto.isbn());
        e.setTitle(dto.title());
        e.setAuthor(dto.author());
        e.setYear(dto.year());
        e = bookRepository.save(e);

        ResponseEntity<BookDTO> resp = ResponseEntity.ok(new BookDTO(e.getBookId(),e.getAuthor(),e.getIsbn(),e.getTitle(),e.getYear()));

        log.info("saveBook() {} ", uuid);

        observation.stop();

        return resp;
    }

    @PutMapping(produces = MediaType.APPLICATION_JSON_VALUE, consumes = MediaType.APPLICATION_JSON_VALUE)
    @Transactional
    public ResponseEntity<BookDTO> update(@RequestBody BookDTO dto) {

        Observation observation = Observation.start("update", observationRegistry);

        UUID uuid = UUID.randomUUID();
        log.info("updateBook() {} running", uuid);

        Book e = this.bookRepository.findByIsbn(dto.isbn());
        e.setAuthor(dto.author());
        e = this.bookRepository.save(e);

        BookDTO bookDto = new BookDTO(e.getBookId(),e.getAuthor(),e.getIsbn(),e.getTitle(),e.getYear());

        log.info("updateBook() {} executed", uuid);

        observation.stop();

        return ResponseEntity.ok(bookDto);
    }


}