receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true
  logging:
    #verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging,otlp]