thread-mode: ${THREAD_MODE}

spring:
  application:
    name: spring-app-${THREAD_MODE}
  threads:
    virtual:
      enabled: ${VIRTUAL_THREAD}

  #  datasource:
#    url: jdbc:postgresql://db-service:5432/postgres?currentSchema=library
#    username: postgres
#    password: postgres
#
#  jpa:
#    generate-ddl: 'false'
#    database: POSTGRESQL
#    properties:
#      hibernate:
#        default_schema: library
#    show-sql: 'false'
#    hibernate:
#      ddl-auto: none
#  sql:
#    init:
#      platform: postgres

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    generate-ddl: false
    database:
    show-sql: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: '8080'
  #tomcat:
  #  mbeanregistry:
  #    enabled: true

management:
  endpoint:
    metrics:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  metrics:
    tags:
      application: spring-app
  otlp:
    tracing:
      endpoint: http://otel:4318/v1/traces
  #zipkin:
  #  tracing:
  #    endpoint: http://tempo:9411

#logging.pattern.level: "trace_id=%mdc{traceId} span_id=%mdc{spanId} %p"
logging:
  level:
    gae: INFO
    org.springframework.cloud.kubernetes: TRACE