thread-mode: ${THREAD_MODE}

spring:
  threads:
    virtual:
      enabled: ${VIRTUAL_THREAD}

  datasource:
    username: postgres
    url: jdbc:postgresql://db-service:5432/postgres?currentSchema=library
    password: postgres

  jpa:
    generate-ddl: 'false'
    database: POSTGRESQL
    properties:
      hibernate:
        default_schema: library
    show-sql: 'false'
    hibernate:
      ddl-auto: none
  sql:
    init:
      platform: postgres

server:
  port: '8080'
  #tomcat:
  #  mbeanregistry:
  #    enabled: true

management:
  endpoint:
    metrics:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: spring-app